config/routes.rb
SocialLibrary::Application.routes.draw do
  resources :book_users

  resources :books do
    get :search, :on => :collection
    get :find, :on => :collection
  end

  resources :users

  root :to => 'books#search'

  resources :books do
  end

end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :book_id, :isbn, :name
end

app/models/book_user.rb
class BookUser < ActiveRecord::Base
  attr_accessible :book_id, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :user_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/book_users_controller.rb
class BookUsersController < ApplicationController
  # GET /book_users
  # GET /book_users.json
  def index
    @book_users = BookUser.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @book_users }
    end
  end

  # GET /book_users/1
  # GET /book_users/1.json
  def show
    @book_user = BookUser.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book_user }
    end
  end

  # GET /book_users/new
  # GET /book_users/new.json
  def new
    @book_user = BookUser.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book_user }
    end
  end

  # GET /book_users/1/edit
  def edit
    @book_user = BookUser.find(params[:id])
  end

  # POST /book_users
  # POST /book_users.json
  def create
    @book_user = BookUser.new(params[:book_user])

    respond_to do |format|
      if @book_user.save
        format.html { redirect_to @book_user, notice: 'Book user was successfully created.' }
        format.json { render json: @book_user, status: :created, location: @book_user }
      else
        format.html { render action: "new" }
        format.json { render json: @book_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /book_users/1
  # PUT /book_users/1.json
  def update
    @book_user = BookUser.find(params[:id])

    respond_to do |format|
      if @book_user.update_attributes(params[:book_user])
        format.html { redirect_to @book_user, notice: 'Book user was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /book_users/1
  # DELETE /book_users/1.json
  def destroy
    @book_user = BookUser.find(params[:id])
    @book_user.destroy

    respond_to do |format|
      format.html { redirect_to book_users_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def find
    @books = Book.where([ "name LIKE ?", "%#{params[:query]}%"])

    render :index
  end
  
  def search
    
    respond_to do |format|
      format.html # search.html.erb
      format.json { render jason: @books }
    end
  end

  # GET /books
  # GET /books.json
  def index
    @books = Book.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book])

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render json: @book, status: :created, location: @book }
      else
        format.html { render action: "new" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_users_helper.rb
module BookUsersHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_users/_form.html.erb
<%= form_for(@book_user) do |f| %>
  <% if @book_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book_user.errors.count, "error") %> prohibited this book_user from being saved:</h2>

      <ul>
      <% @book_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :book_id %><br />
    <%= f.text_field :book_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/book_users/edit.html.erb
<h1>Editing book_user</h1>

<%= render 'form' %>

<%= link_to 'Show', @book_user %> |
<%= link_to 'Back', book_users_path %>

app/views/book_users/index.html.erb
<h1>Listing book_users</h1>

<table>
  <tr>
    <th>User</th>
    <th>Book</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @book_users.each do |book_user| %>
  <tr>
    <td><%= book_user.user_id %></td>
    <td><%= book_user.book_id %></td>
    <td><%= link_to 'Show', book_user %></td>
    <td><%= link_to 'Edit', edit_book_user_path(book_user) %></td>
    <td><%= link_to 'Destroy', book_user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Book user', new_book_user_path %>

app/views/book_users/new.html.erb
<h1>New book_user</h1>

<%= render 'form' %>

<%= link_to 'Back', book_users_path %>

app/views/book_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @book_user.user_id %>
</p>

<p>
  <b>Book:</b>
  <%= @book_user.book_id %>
</p>


<%= link_to 'Edit', edit_book_user_path(@book_user) %> |
<%= link_to 'Back', book_users_path %>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :book_id %><br />
    <%= f.text_field :book_id %>
  </div>
  <div class="field">
    <%= f.label :isbn %><br />
    <%= f.text_field :isbn %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Listing books</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Book</th>
    <th>Isbn</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @books.each do |book| %>
  <tr>
    <td><%= book.name %></td>
    <td><%= book.book_id %></td>
    <td><%= book.isbn %></td>
    <td><%= link_to 'Show', book %></td>
    <td><%= link_to 'Edit', edit_book_path(book) %></td>
    <td><%= link_to 'Destroy', book, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/search.html.erb
<h1>Search books</h1>

<%= form_tag [ :find, :books ], :method => :get do %>
    <%= text_field_tag "query", params[:query] %>
    <%= submit_tag "search" %>
<% end %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @book.name %>
</p>

<p>
  <b>Book:</b>
  <%= @book.book_id %>
</p>

<p>
  <b>Isbn:</b>
  <%= @book.isbn %>
</p>


<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SocialLibrary</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.user_id %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>User:</b>
  <%= @user.user_id %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>